before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/dlc/main.go
    binary: dlc
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
archives:
  - replacements:
      linux: Linux
      windows: Windows
      386: x86
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"